FROM quay.io/centos/centos:7
RUN \
  yum -y update && \
  yum install -y \
    dnf \
    dnf-plugins-core \
    gcc \
    krb5-devel \
    libffi-devel \
    python-devel \
    python-librepo \
    python-requests \
    rpm-build  && \
  yum install -y epel-release && \
  yum install -y \
    python-defusedxml \
    python-pip \
    python-psycopg2 && \
  yum clean all && \
  pip install -U 'pip==9.0.1' && \
  pip install -U tox
