FROM quay.io/centos/centos:stream8

RUN \
  dnf -y update --nodocs --setopt=install_weak_deps=False && \
  dnf install -y --nodocs --setopt=install_weak_deps=False epel-release && \
  dnf install -y --nodocs --setopt=install_weak_deps=False \
  gcc \
  glibc-langpack-en \
  krb5-devel \
  python3-defusedxml \
  python3-devel \
  python3-librepo \
  python3-setuptools \
  python3-tox \
  rpm-build && \
  dnf clean all
