FROM centos:8

RUN \
  dnf -y update --nodocs --setopt=install_weak_deps=False && \
  dnf install -y epel-release && \
  dnf install -y \
  'dnf-command(download)' \
  gcc \
  git \
  glib2-devel \
  glibc-langpack-en \
  krb5-devel \
  libffi-devel \
  libxml2-devel \
  make \
  openssl-devel \
  python3-devel \
  python3-librepo \
  python3-pip \
  python3-rpm \
  python3-tox \
  redhat-rpm-config \
  rpm-build \
  rpm-devel \
  sqlite-devel \
  yum-utils && \
  dnf clean all
